### ISSUE TITLE
Tidy up solaris linker flag handling.

### ISSUE THREAD

**Issue by v00d00** [v00d00/mediatomb#20]
@whorfin 

What is the "correct" way to get the currently hardcoded solaris flags? pkg-config or something else? Do you know any other CMake-using packages that detect these sorts of things?

**Comment by whorfin** [comment]
That's an excellent question; I stopped at "well, this works"
The fact that the Lib_UUID package resolution doesn't find -luuid seems suspicious, as does the non-explicit iconv handling.
On the other hand, it's typical to require some kind of manual intervention on Solaris to get -lnsl -lsocket happening for socket code.

There's a friendlier library-finding mechanism i might try, but will need help to test on other platforms, if you like..

**Comment by whorfin** [comment]
OK, pull incoming
