### ISSUE TITLE
Autoscan directories are not scanned at start-up

### ISSUE THREAD

**Issue by gburca** [v00d00/mediatomb#33]
The `config.xml` file allows the user to specify directories to be auto-scanned (`import - scripting - autoscan`). When the application starts up with no pre-existing database, a new database is created, but the directories listed in the config file are not scanned to populate the database.

**Comment by v00d00** [comment]
Being lazy here, can you post some example XML?

**Comment by gburca** [comment]
I looked at it closer, and it turns out I placed the `<autoscan>` in the wrong section. After fixing that I hit another snag. Will open a new issue for it though.

For reference, here's where the autoscan entry goes:

```
<config ...>
  ...
  <import ...>
    <autoscan use-inotify="auto">
      <directory location="/some/data/path/MediaTomb"
        mode="inotify" level="full" recursive="yes" hidden-files="no"/>
      <directory location="/some/timed/path"
        mode="timed" level="full" recursive="yes" hidden-files="no" interval="86400"/>
    </autoscan>
  </import>
</config>
```
