### ISSUE TITLE
SIGHUP causes serving port to change, and other badness

### ISSUE THREAD

**Issue by whorfin** [v00d00/mediatomb#34]
Sometimes SIGHUP is completely ignored.
Often, SIGHUP messes with the configured port.

[anecdotal reports over in #32 ]

In quick summary, one can observe in the logfile, and confirm as behavior, that the "Initialized port" is incremented, and not the actual requested port, each time a SIGHUP is sent to mediatomb.  Eventually the requested port will be selected, if luck smiles upon one.

Also src/storage/sql_storage.cc:936 sometimes throws an exception

**Comment by v00d00** [comment]
The signal logic in `main.cc` is a bit gross.

I guess we need to enhance `ConfigManager` to add a `reload()` method and then replace all that cruft with a call on `SIGHUP`, or shut down otherwise.

Either that or detect if the interface, ip or port have changed and if not leave the `Server` alone.

**Comment by v00d00** [comment]
What settings are you changing before SIGHUP'ing out of interest? Scanned directories?

**Comment by whorfin** [comment]
Recently was changing "ui enabled" on/off, while debugging the issues with the description.xml file
Historically, I'd use a SIGHUP kick to force a rescan.

**Comment by whorfin** [comment]
Also confirmed:
after SIGHUP, autoscan stops
I've created a test case where a subdir of an autoscan directory has a permission problem as far as the mediatomb server process is concerned.  So I can see a heartbeat of
ERROR: Failed to stat
those heartbeats [approximately every autoscan interval] stop after SIGHUP

**Comment by whorfin** [comment]
...some more information:

The port-advancing behavior is easily tickled by SIGHUP, but there seems to be a more fundamental issue that ports are not cleanly shut down/cleaned up in general.

If I simply "restart" mediatomb via my normal OS mechanism [kill, wait for kill, start], I often see the port advance as well.  It is much more likely to not come back up with the desired port if a stream were playing or the web GUI in use.  The fancy auto-refreshing of the web GUI may not be helping.

**Comment by whorfin** [comment]
I think I may have found the port-advancing problem.

in pupnp, upnp/src/genlib/miniserver/miniserver.c doesn't use SO_REUSEADDR, which seems to be a mistake.  This will cause sockets in TIME_WAIT state to block port connection when restarting the server.
The comment says
	 * TURN ON the reuseaddr_on option to use the option. */
but this seems impossible - reuseaddr_on is a local int, initialized to 0 and never set elsewhere
Some cursory git blaming doesn't show it ever being settable since creation of the library, though again that was a cursory glance

Patching pupnp to properly use SO_REUSEADDR should fix things; any of you in contact with the maintainer?

Cheers

**Comment by gburca** [comment]
Yes, I submitted a patch to pupnp not too long ago. They were pretty responsive.

**Comment by v00d00** [comment]
My patch has been merged in upnp. Can you give it a try?

**Comment by whorfin** [comment]
Thanks much!
Failed, perhaps unsurprisingly, as that code path is old 'n busted.
I made a quick fix, and now things are glorious.
https://github.com/mrjimenez/pupnp/pull/27

...hoping it will be merged

**Comment by whorfin** [comment]
pupnp fix has been merged
IMHO building pupnp with the --enable-reuseaddr option is necessary if you rely on configured DLNA addressess rather than discovery

I'm happy to have this issue closed, as I now have a fully functional installation using server restart instead of SIGHUP, which still sometimes is ignored or throws errors in the sql code path above.
