### ISSUE TITLE
compiling on debian jessie

### ISSUE THREAD

**Issue by monolifed** [v00d00/mediatomb#41]
- I had to build and install pupnp with `configure --enable-ipv6`
- for some reason target specific cxx version settings in the cmakelists.txt do not work so I had to change the global flags `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++14")`
- src/tools.cc raised a problem so changed to `log_debug("Looking for '%s'\n", ip.c_str());`

**Comment by v00d00** [comment]
Thanks for letting me know!

See the fixes.
