### ISSUE TITLE
autoscan only runs once

### ISSUE THREAD

**Issue by whorfin** [v00d00/mediatomb#42]
I incorrectly associated this with SIGHUP because of bundled changes.
While I'm not positive, since the reported version in logging doesn't include git revision [maybe it should?] I believe this showed up with 49a9e4d38aed56c39290133c6dc50ba339201cea

I know that I started seeing the bad behavior along with the "event is ok" message which was introduced very shortly after that commit.  49a9e4d38aed56c39290133c6dc50ba339201cea changed a bunch of
things related to the autoscan timer, hence my suspicion.

I've created a test case where a subdir of an autoscan directory has a permission problem as far as the mediatomb server process is concerned. So I can see a heartbeat of
ERROR: Failed to stat
those heartbeats only happen once at the start of mediatomb now, rather than approximately every autoscan interval

**Comment by whorfin** [comment]
Note - there is no inotify on Solaris, so I am using autoscan as so:

    <autoscan use-inotify="no">
        <directory location="/tank/dirA/dir1 mode="timed" interval="3600"
                level="full" recursive="yes" hidden-files="no"/>
        <directory location="/tank/dirA/dir2" mode="timed" interval="3600"
                level="full" recursive="yes" hidden-files="no"/>
        <directory location="/tank/dirB/dir1" mode="timed" interval="3600"
                level="full" recursive="yes" hidden-files="no"/>
    </autoscan>

Some day using File Events Notification (FEN) for the Solaris/OmniOS case would be groovy, or
perhaps better still building the asynchronous file change scanning on top of something cross-platform like the fsnotify module in Go [which isn't fully cross-platform yet but makes promises]:
https://fsnotify.org/
https://github.com/fsnotify/fsnotify

**Comment by v00d00** [comment]
@gburca any chance you can take a look?

**Comment by gburca** [comment]
It's on my ToDo list, but I'm a little backed up for the next month or so. The 49a9e4d commit was pretty massive because everything was tied together. I'll see if I can take a crack at it tonight.

**Comment by v00d00** [comment]
I had a look at this tonight couldn't see anything obvious, I will keep looking tomorrow if I have time.

**Comment by gburca** [comment]
It doesn't look like `addTimerSubscriber()` is ever called.

**Comment by v00d00** [comment]
There is a commented out method in `autoscan.cc` void `AutoscanList::subscribeDir()`.

But it was commented out before also, so not sure how this was supposed to work.

**Comment by v00d00** [comment]
Can you try with 0f358ecb44cb7efa94b07e66623be1da0821660b?

**Comment by whorfin** [comment]
Fixed!

nice, thanks
