### ISSUE TITLE
Question: How to move away from Vanilla

### ISSUE THREAD

**Issue by antenore** [v00d00/mediatomb#48]
Thanks a lot for resurrecting this amazing project!!!

I've a media server running the old mediatomb and I was planning to use the master branch.

Is the old database compatible or should I just drop the old one and recreate it?

Sorry for asking a question here, but I didn't find a more suitable place.

**Comment by antenore** [comment]
Closing... I'm getting old, sorry.

**Comment by v00d00** [comment]
No problem in asking. You can use your existing DB without changes. To get more artwork you will probably want to recreate it, though.
