### ISSUE TITLE
mediatomb master: cannot be built on Ubuntu 16.10??

### ISSUE THREAD

**Issue by count00zero** [v00d00/mediatomb#52]
Hi,

I've got one question regarding the master branch and ubuntu 16.10.
I am not able to build it errorfree!
Although ffmpeg and libav  there is the following error with cmake:

```
-- Could NOT find LibAV (missing:  LIBAV_ROOT_DIR LIBAV_AVDEVICE_LIBRARY LIBAV_AVFILTER_LIBRARY) (found version "ffmpeg version 3.0.7-0ubuntu0.16.10.1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu12) 20161005

CMake Error at CMakeLists.txt:481 (message):
  FFMpeg/LibAV not found
```

Is there any kind of solution which already came up?

Thanks a lot in advance and BR,
count

**Comment by v00d00** [comment]
Do you have the `libavcodec-dev.` package installed?

**Comment by count00zero** [comment]
yes it is installed:
libavcodec-dev - Version (7:3.0.7-0ubuntu0.16.10.1)

**Comment by count00zero** [comment]
I read somewhere the following: Ubuntu 16.10 has switched from libav back to ffmpeg again.

I also had build issues with minidlna; there I got the hint from the Juastin Maggard to chaneg a view lines in libav.h, which did the trick for me.
But I've no clue at all (sorry ;-) ) how to outmanoeuvre that ffmpeg/libav obstacle with your mediatomb fork.

**Comment by count00zero** [comment]
Those were the changes I made to minidlna - libav.h :

FFmpeg 3.0, as used on Ubuntu Yakkety, did not include the codecpar
changes, although it uses the same library major version. So refine the
libavformat version check to sort that out.
```
---
 libav.h | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/libav.h b/libav.h
index f04bb42..e706240 100644
--- a/libav.h
+++ b/libav.h
@@ -57,6 +57,8 @@
 #include <avformat.h>
 #endif
 
+#define USE_CODECPAR LIBAVFORMAT_VERSION_INT >= ((57<<16)+(50<<8)+100)
+
 #ifndef FF_PROFILE_H264_BASELINE
 #define FF_PROFILE_H264_BASELINE 66
 #endif
@@ -166,7 +168,7 @@ lav_get_interlaced(AVStream *s)
 #endif
 }
 
-#if LIBAVCODEC_VERSION_MAJOR >= 57
+#if USE_CODECPAR
 #define lav_codec_id(s) s->codecpar->codec_id
 #define lav_codec_type(s) s->codecpar->codec_type
 #define lav_codec_tag(s) s->codecpar->codec_tag
@@ -195,7 +197,7 @@ lav_get_interlaced(AVStream *s)
 static inline uint8_t *
 lav_codec_extradata(AVStream *s)
 {
-#if LIBAVCODEC_VERSION_MAJOR >= 57
+#if USE_CODECPAR
 	if (!s->codecpar->extradata_size)
 		return NULL;
 	return s->codecpar->extradata;
-- 
```

**Comment by v00d00** [comment]
You also need `libavformat-dev`

**Comment by v00d00** [comment]
So tried it in a 16.10 container and you are right, lots of lovely codecpar issues. eg

```
In file included from /mediatomb/src/common.h:37:0,
                 from /mediatomb/src/config_manager.h:36,
                 from /mediatomb/src/metadata/ffmpeg_handler.cc:65:
/mediatomb/src/metadata/ffmpeg_handler.cc:199:45: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'; did you mean 'codec'?
                                         st->codecpar->codec_tag, fourcc);
```

**Comment by count00zero** [comment]
»libavformat-dev« already installed; version (7:3.0.7-0ubuntu0.16.10.1).

Yeah, that issues are really lovely ;-)
Did a new pull; had to disable lastfmlib (donnu why, everything is here) and ... cmake threw no errors ... will try to continue now.

.....

as you mentioned: `ffmpeg_handler.cc:221:12: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?`
****

**Comment by count00zero** [comment]
I'm really curious how Stephen Czetty made it (static?) .... I just installed the precompiled version directly from the ubuntu ppa he maintains => that is running now!

**Comment by v00d00** [comment]
Probably you have no ffmpeg support 👍

**Comment by count00zero** [comment]
ha ... that maybe!
Cause I can easily compile with -DWITH_AVCODEC=0 => maybe that's the way it's done @Stephens end; will ask him :)
Thanks anyway!!

BR,
count

**Comment by v00d00** [comment]
https://github.com/v00d00/mediatomb/commit/32efd463f138557c54535225d84136df95bab3dd should fix this.

Can you give it a try?

**Comment by v00d00** [comment]
@count00zero any chance you can test?

**Comment by v00d00** [comment]
Going to assume this is sorted.

**Comment by count00zero** [comment]
Hi and sorry for late reply.
I've been busy @ work and with the family.

THANKS al lot!
It worked and everything could be built without errors (the warnings don't count)..

Thanks again and great job!

BR,
count
