### ISSUE TITLE
pkill -TERM never seems to succeed, -HUP ignored

### ISSUE THREAD

**Issue by whorfin** [v00d00/mediatomb#53]
first -TERM:
 INFO: MediaTomb shutting down. Please wait...

I can wait all day, no exit

second -TERM:
 INFO: Mediatomb still shutting down, signal again to kill.

same thing

third -TERM:
 ERROR: Clean shutdown failed, killing MediaTomb!

Along those same lines, -HUP now does nothing

Is this related to the timer/nullptr changes?

**Comment by v00d00** [comment]
It may be related to the timer changes.

Splat one bug and more appear 😆 

![](http://24.media.tumblr.com/6a4e0b2edf41ff29997ca569119610b6/tumblr_n2ft5cf1Mq1sm39ito1_500.gif)

**Comment by v00d00** [comment]
Hmmm so what I didnt realise when I refactored that code is that the code in `main.cc` was essentially using the timer code as its loop! That doesnt really make sense to me.

I will probably give the timer its own thread, and let `main` just do its own thing.
