### ISSUE TITLE
The web interface is not working

### ISSUE THREAD

**Issue by gburca** [v00d00/mediatomb#6]
Commit 5a7c4f3 broke the web interface. See comment on the commit for more details.

**Comment by v00d00** [comment]
Yeah vanilla libupnp has no header methods in version 1.6, so I it's a WIP to port it over to the 1.8 API.

**Comment by Corin-EU** [comment]
First of all, a super big thank you for reviving Mediatomb and bring it back from near death after it started suffering code rot with ffmpeg/libav and libffmpegthumbnailer library changes.

So the web login problem is not some misconfiguration problem then, because when I enter password, it says on login page and log file just keeps repeating

DEBUG: [/srv/repository/git/mediatomb/src/web_callbacks.cc:62] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token/index.html, Path: (null)

It would be nice to get mediatomb up and running again.

**Comment by v00d00** [comment]
Hi Guys,

This should be sorted in 9939adef7e98ca4d3dfac2ef9507687363eaac0a.

You will need to build against libupnp 1.8.

Thanks!

**Comment by gburca** [comment]
I tried the web interface with 2a1bfdd and it's still not working on my system. Tried it both with accounts enabled="yes" and enabled="no" and it's still prompting for username/password and refusing to accept the configured username/password. @Corin-EU, is it working for you?

**Comment by Corin-EU** [comment]
I have built the latest v00d00 mediatomb  **r.11dea73** with the latest mrjiminez pupnp **r.7dbf417** on Debian 8.6 

      ldd /usr/local/bin/mediatomb   | grep upnp
         libupnp-1.8.so.10 => /usr/local/lib/libupnp-1.8.so.10 (0x76dd9000)

      ldd /usr/local/bin/mediatomb   | grep xml
         libixml-1.8.so.10 => /usr/local/lib/libixml-1.8.so.10 (0x76d9d000)

      ldd /usr/local/bin/mediatomb   | grep mozjs
         libmozjs185.so.1.0 => /usr/lib/libmozjs185.so.1.0 (0x7679d000)

but am still unable to get any login response to the web server page with the same debug messages

      2016-12-29 21:13:54   DEBUG: [/srv/repository/git/mediatomb/src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token, Path: (null)
      2016-12-29 21:13:54   DEBUG: [/srv/repository/git/mediatomb/src/web_callbacks.cc:148] web_open(): web_open(): /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token
      2016-12-29 21:13:54   DEBUG: [/srv/repository/git/mediatomb/src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token, Path: (null)

As a test, I have built the latest mediatomb-vanilla **r.227920f** and that works (with the same config.xml and similar build options except youtube is disabled).

One possibly significant difference is that I see that mediatomb (13) includes dynamic linkage to libjson-c.so.2 (a Debian package installed library) whereas mediatomb-vanilla (12) has no such libjson-c.so linkage whatsoever.

Any advice on how to resolve this problem please?

**Comment by v00d00** [comment]
@Corin-EU can you open a new issue please? I suspect that our build system may be detecting an older libupnp, but we can investigate in the new issue.
